### ISSUE TITLE
Data type lost in Model after load

### ISSUE THREAD

**Issue by insky** [smetana/tipy#2]
But test passed on CircleCI. May be system-dependent bug.

[Screenshot](https://www.dropbox.com/s/udy74nfi8mxbtvc/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-08-23%2006.04.06.png?dl=0)

**Comment by smetana** [comment]
Fixed in 9c4c44d73cc61de31aae08cefc7ed24a487fd044
